runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /scripts
  static_dir: scripts
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

skip_files:
- ^train.csv
- ^test.csv
- ^tox.csv
- ^sample_submission.csv
