runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /scripts
  static_dir: scripts
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

skip_files:
- ^train.csv
- ^test.csv
- ^tox.csv
- ^test.txt
- ^test2.txt
- ^poster.pdf
- ^poster.ppt
- ^sample_submission.csv
- ^.git/objects/pack/pack-0a1f6f1743ffd9387d90261e979c6440a688fb6d.pack
